### Get all the information about a portfolio
GET http://localhost:3000/api/portfolio/3e8a5c72cd6cb54db05bd33f945448b5db38f9adededbe157d48fb51fe84f539

### Get transactions grouped by currency
GET http://localhost:3000/api/portfolio/currencies/3e8a5c72cd6cb54db05bd33f945448b5db38f9adededbe157d48fb51fe84f539

### Get transactions grouped by type
GET http://localhost:3000/api/portfolio/investmentsType/3e8a5c72cd6cb54db05bd33f945448b5db38f9adededbe157d48fb51fe84f539

### Get transactions grouped by entity
GET http://localhost:3000/api/portfolio/entities/3e8a5c72cd6cb54db05bd33f945448b5db38f9adededbe157d48fb51fe84f539