### Positions call paginated
GET http://localhost:3000/api/position

### Positions call with limit
GET http://localhost:3000/api/position?limit=2

### Positions call by id
GET http://localhost:3000/api/position/9da02c3f574e30a8daaa09460f2a87ef29c5a0fbeee618fb7e4538090dc8b885

### Positions by portfolio id (client_id)
GET http://localhost:3000/api/position/portfolio/3e8a5c72cd6cb54db05bd33f945448b5db38f9adededbe157d48fb51fe84f539
